import VehicleSubscription, {
    Vehicle,
    SubscriptionPlanType,
    SubscriptionStatus,
    BillingFrequency,
    CarWashLocation,
    PaymentMethod,
} from "../models/VehicleSubscription";

// Shared car wash locations
const carWashLocations: CarWashLocation[] = [
    {
        id: "loc-001",
        name: "Sparkle Clean Downtown",
        address: "123 Main Street",
        city: "Springfield",
        state: "IL",
        zip: "62701",
        phone: "(217) 555-0123",
        email: "downtown@sparkleclean.com",
        website: "www.sparkleclean.com/downtown",
    },
    {
        id: "loc-002",
        name: "Sparkle Clean Westside",
        address: "456 West Avenue",
        city: "Springfield",
        state: "IL",
        zip: "62704",
        phone: "(217) 555-0456",
        email: "westside@sparkleclean.com",
        website: "www.sparkleclean.com/westside",
    },
    {
        id: "loc-003",
        name: "Sparkle Clean Airport",
        address: "789 Airport Road",
        city: "Springfield",
        state: "IL",
        zip: "62707",
        phone: "(217) 555-0789",
        email: "airport@sparkleclean.com",
        website: "www.sparkleclean.com/airport",
    },
    {
        id: "loc-004",
        name: "Premium Auto Spa",
        address: "321 Luxury Lane",
        city: "Metropolis",
        state: "NY",
        zip: "10001",
        phone: "(212) 555-0321",
        email: "info@premiumautospa.com",
        website: "www.premiumautospa.com",
    },
    {
        id: "loc-005",
        name: "Quick Wash Express",
        address: "555 Fast Lane",
        city: "Gotham",
        state: "NJ",
        zip: "07001",
        phone: "(201) 555-0555",
        email: "express@quickwash.com",
    },
];

export const exampleVehicleSubscriptions: VehicleSubscription[] = [
    {
        id: "sub-001",
        customerId: "cust-1001",
        planType: SubscriptionPlanType.PREMIUM,
        planFeatures: {
            maxVehicles: 3,
            maxWashesPerMonth: 12,
            detailingIncluded: true,
        },
        status: SubscriptionStatus.ACTIVE,
        locations: [
            carWashLocations[0],
            carWashLocations[1],
            carWashLocations[2],
        ],
        vehicles: [
            {
                id: "veh-001",
                vin: "1HGCM82633A123456",
                make: "Honda",
                model: "Accord",
                year: 2023,
                color: "Silver",
                licensePlate: "ABC123",
                addedAt: new Date("2023-06-01").toISOString(),
            },
            {
                id: "veh-002",
                vin: "5UXWX9C57E0123456",
                make: "BMW",
                model: "X3",
                year: 2023,
                color: "Black",
                licensePlate: "XYZ789",
                addedAt: new Date("2024-01-15").toISOString(),
            },
        ],
        startDate: new Date("2023-06-01").toISOString(),
        billingInfo: {
            amount: 89.99,
            currency: "USD",
            frequency: BillingFrequency.MONTHLY,
            nextBillingDate: new Date("2025-08-01").toISOString(),
            lastBillingDate: new Date("2025-07-01").toISOString(),
            paymentMethod: {
                id: "pm-001",
                type: "card",
                details: {
                    cardBrand: "Visa",
                    cardLast4: "4242",
                },
            },
        },
        createdAt: new Date("2023-05-25").toISOString(),
        updatedAt: new Date("2025-07-01").toISOString(),
    },
    {
        id: "sub-002",
        customerId: "cust-1002",
        planType: SubscriptionPlanType.BASIC,
        planFeatures: {
            maxVehicles: 1,
            maxWashesPerMonth: 4,
            detailingIncluded: false,
        },
        status: SubscriptionStatus.ACTIVE,
        locations: [carWashLocations[3]],
        vehicles: [
            {
                id: "veh-003",
                vin: "1G1BC5SM8G7123456",
                make: "Chevrolet",
                model: "Cruze",
                year: 2022,
                color: "Blue",
                licensePlate: "DEF456",
                addedAt: new Date("2024-03-01").toISOString(),
            },
        ],
        startDate: new Date("2024-03-01").toISOString(),
        billingInfo: {
            amount: 29.99,
            currency: "USD",
            frequency: BillingFrequency.MONTHLY,
            nextBillingDate: new Date("2025-08-01").toISOString(),
            lastBillingDate: new Date("2025-07-01").toISOString(),
            paymentMethod: {
                id: "pm-002",
                type: "card",
                details: {
                    cardBrand: "Mastercard",
                    cardLast4: "5555",
                },
            },
            discount: {
                percentage: 10,
                reason: "New customer promotion",
                validUntil: new Date("2025-03-01").toISOString(),
            },
        },
        createdAt: new Date("2024-02-25").toISOString(),
        updatedAt: new Date("2025-07-01").toISOString(),
    },
    {
        id: "sub-003",
        customerId: "cust-1003",
        planType: SubscriptionPlanType.STANDARD,
        planFeatures: {
            maxVehicles: 2,
            maxWashesPerMonth: 8,
            detailingIncluded: false,
        },
        status: SubscriptionStatus.PAUSED,
        locations: [carWashLocations[4]],
        vehicles: [
            {
                id: "veh-004",
                vin: "JM1CW2BL8E0123456",
                make: "Mazda",
                model: "CX-5",
                year: 2023,
                color: "Red",
                licensePlate: "GHI789",
                addedAt: new Date("2023-09-01").toISOString(),
            },
        ],
        startDate: new Date("2023-09-01").toISOString(),
        pausedAt: new Date("2025-06-15").toISOString(),
        billingInfo: {
            amount: 49.99,
            currency: "USD",
            frequency: BillingFrequency.MONTHLY,
            nextBillingDate: new Date("2025-09-01").toISOString(),
            lastBillingDate: new Date("2025-06-01").toISOString(),
            paymentMethod: {
                id: "pm-003",
                type: "paypal",
                details: {
                    paypalEmail: "carol.lee@example.com",
                },
            },
        },
        createdAt: new Date("2023-08-25").toISOString(),
        updatedAt: new Date("2025-06-15").toISOString(),
    },
    {
        id: "sub-004",
        customerId: "cust-1004",
        planType: SubscriptionPlanType.ENTERPRISE,
        planFeatures: {
            maxVehicles: 5,
            maxWashesPerMonth: 50,
            detailingIncluded: true,
        },
        status: SubscriptionStatus.ACTIVE,
        locations: carWashLocations,
        vehicles: [
            {
                id: "veh-005",
                vin: "WBAJB9C51KB123456",
                make: "BMW",
                model: "530i",
                year: 2024,
                color: "White",
                licensePlate: "JKL012",
                addedAt: new Date("2024-06-01").toISOString(),
            },
            {
                id: "veh-006",
                vin: "2T1BURHE3JC123456",
                make: "Toyota",
                model: "Camry",
                year: 2023,
                color: "Gray",
                licensePlate: "MNO345",
                addedAt: new Date("2024-06-01").toISOString(),
            },
            {
                id: "veh-007",
                vin: "1FTFW1ET5DF123456",
                make: "Ford",
                model: "F-150",
                year: 2023,
                color: "Blue",
                licensePlate: "PQR678",
                addedAt: new Date("2024-08-15").toISOString(),
            },
        ],
        startDate: new Date("2024-06-01").toISOString(),
        billingInfo: {
            amount: 199.99,
            currency: "USD",
            frequency: BillingFrequency.MONTHLY,
            nextBillingDate: new Date("2025-08-01").toISOString(),
            lastBillingDate: new Date("2025-07-01").toISOString(),
            paymentMethod: {
                id: "pm-004",
                type: "bank_transfer",
                details: {
                    bankAccountLast4: "9876",
                },
            },
            discount: {
                amount: 50,
                reason: "Enterprise volume discount",
                validUntil: new Date("2026-06-01").toISOString(),
            },
        },
        createdAt: new Date("2024-05-20").toISOString(),
        updatedAt: new Date("2025-07-01").toISOString(),
    },
    {
        id: "sub-005",
        customerId: "cust-1005",
        planType: SubscriptionPlanType.STANDARD,
        planFeatures: {
            maxVehicles: 2,
            maxWashesPerMonth: 8,
            detailingIncluded: false,
        },
        status: SubscriptionStatus.ACTIVE,
        locations: [carWashLocations[0], carWashLocations[1]],
        vehicles: [
            {
                id: "veh-008",
                vin: "3VWDP7AJ5EM123456",
                make: "Volkswagen",
                model: "Jetta",
                year: 2022,
                color: "White",
                licensePlate: "STU901",
                addedAt: new Date("2024-04-01").toISOString(),
            },
            {
                id: "veh-009",
                vin: "KMHD84LF6HU123456",
                make: "Hyundai",
                model: "Elantra",
                year: 2021,
                color: "Silver",
                licensePlate: "VWX234",
                addedAt: new Date("2024-06-15").toISOString(),
            },
        ],
        startDate: new Date("2024-04-01").toISOString(),
        billingInfo: {
            amount: 49.99,
            currency: "USD",
            frequency: BillingFrequency.MONTHLY,
            nextBillingDate: new Date("2025-08-01").toISOString(),
            lastBillingDate: new Date("2025-07-01").toISOString(),
            paymentMethod: {
                id: "pm-005",
                type: "card",
                details: {
                    cardBrand: "Discover",
                    cardLast4: "8888",
                },
            },
        },
        createdAt: new Date("2024-03-28").toISOString(),
        updatedAt: new Date("2025-07-01").toISOString(),
    },
    {
        id: "sub-006",
        customerId: "cust-1006",
        planType: SubscriptionPlanType.PREMIUM,
        planFeatures: {
            maxVehicles: 3,
            maxWashesPerMonth: 12,
            detailingIncluded: true,
        },
        status: SubscriptionStatus.CANCELLED,
        locations: [carWashLocations[3]],
        vehicles: [
            {
                id: "veh-010",
                vin: "WA1LFAFP8EA123456",
                make: "Audi",
                model: "Q5",
                year: 2023,
                color: "Black",
                licensePlate: "YZA567",
                addedAt: new Date("2023-11-01").toISOString(),
            },
        ],
        startDate: new Date("2023-11-01").toISOString(),
        cancelledAt: new Date("2025-05-31").toISOString(),
        endDate: new Date("2025-05-31").toISOString(),
        billingInfo: {
            amount: 89.99,
            currency: "USD",
            frequency: BillingFrequency.MONTHLY,
            nextBillingDate: new Date("2025-06-01").toISOString(),
            lastBillingDate: new Date("2025-05-01").toISOString(),
            paymentMethod: {
                id: "pm-006",
                type: "card",
                details: {
                    cardBrand: "American Express",
                    cardLast4: "0001",
                },
            },
        },
        createdAt: new Date("2023-10-28").toISOString(),
        updatedAt: new Date("2025-05-31").toISOString(),
    },
];
