import { User, Customer } from "../models/User.ts";

export const customers: Customer[] = [
    {
        id: "cust-1001",
        firstName: "Alice",
        lastName: "Johnson",
        email: "alice.johnson@example.com",
        phone: "1234567890",
        profilePicture: "https://picsum.photos/200",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        password: "securepassword123",
        role: "customer",
        address: {
            street: "123 Elm St",
            city: "Springfield",
            state: "IL",
            zipCode: "62701",
        },
        vehicleSubscriptions: [],
        CSRRequests: [],
    },
    {
        id: "cust-1002",
        firstName: "Bob",
        lastName: "Smith",
        email: "bob.smith@example.com",
        phone: "5555555555",
        profilePicture: "https://picsum.photos/200",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        password: "pretendthisishashed",
        role: "customer",
        address: {
            street: "456 Oak St",
            city: "Metropolis",
            state: "NY",
            zipCode: "10001",
        },
        vehicleSubscriptions: [],
        CSRRequests: [],
    },
    {
        id: "cust-1003",
        firstName: "Carol",
        lastName: "Lee",
        email: "carol.lee@example.com",
        phone: "7777777777",
        profilePicture: "https://picsum.photos/200",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        password: "defnotsecure123",
        role: "customer",
        address: {
            street: "789 Pine St",
            city: "Gotham",
            state: "NJ",
            zipCode: "07001",
        },
        vehicleSubscriptions: [],
        CSRRequests: [],
    },
    {
        id: "cust-1004",
        firstName: "David",
        lastName: "Kim",
        email: "david.kim@example.com",
        phone: "0010010011",
        profilePicture: "https://picsum.photos/200",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        password: "alwaysusesaltkids",
        role: "customer",
        address: {
            street: "321 Maple St",
            city: "Star City",
            state: "CA",
            zipCode: "90210",
        },
        vehicleSubscriptions: [],
        CSRRequests: [],
    },
    {
        id: "cust-1005",
        firstName: "Eve",
        lastName: "Brown",
        email: "eve.brown@example.com",
        phone: "8888888888",
        profilePicture: "https://picsum.photos/200",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        password: "hashedpassword789",
        role: "customer",
        address: {
            street: "654 Cedar St",
            city: "Central City",
            state: "IL",
            zipCode: "62702",
        },
        vehicleSubscriptions: [],
        CSRRequests: [],
    },
    {
        id: "cust-1006",
        firstName: "Frank",
        lastName: "White",
        email: "frank.white@example.com",
        phone: "9998887777",
        profilePicture: "https://picsum.photos/200",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        password: "hashedpassword012",
        role: "customer",
        address: {
            street: "987 Birch St",
            city: "Coast City",
            state: "CA",
            zipCode: "90211",
        },
        vehicleSubscriptions: [],
        CSRRequests: [],
    },
];

export const admins: User[] = [
    {
        id: "csr-001",
        firstName: "Daniel",
        lastName: "Aoulou",
        email: "aouloudan@icloud.com",
        phone: "2223334444",
        profilePicture: "https://picsum.photos/200",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        password: "hashedpassword456",
        role: "admin",
    },
];
